const { Category } = require('../../api/categorie/categorie.model');

module.exports = async function initCategories() {
  const categories = [
    {
      id: 1,
      nom: 'Bois de menuiserie de pays',
      descriptif: 'Bois massifs Français secs - Avivés ou plots - Différentes épaisseurs disponibles',
      path_img: null,
      id_cat_parent: 0,
      slug: 'bois-de-menuiserie-de-pays',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('2024-01-30T10:40:34'),
      updatedAt: new Date('2024-01-30T10:44:15'),
    },
    {
      id: 2,
      nom: 'Charpente',
      descriptif: 'Bois massif traditionnel - Epicéa du Jura - Brut - Traité CL2 - Stocké à l\'abri',
      path_img: null,
      id_cat_parent: 0,
      slug: 'charpente',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 3,
      nom: 'Lame de terrasse',
      descriptif: 'Pin Sylvestre traité CL4 - Exotique - Bambou',
      path_img: null,
      id_cat_parent: 0,
      slug: 'lame-de-terrasse',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 4,
      nom: 'Bardage et clin',
      descriptif: 'Aménagement extérieur - Revetement de façade de maison - D\'Abri de jardin - Pose verticale ou horizontale',
      path_img: null,
      id_cat_parent: 0,
      slug: 'bardage-clin',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 5,
      nom: 'Bois de menuiserie exotique',
      descriptif: 'Bois Massif d\'origine Afrique - Asie - Amérique du Nord - Amérique du Sud - Avivés - Différentes épaisseurs disponibles',
      path_img: null,
      id_cat_parent: 0,
      slug: 'bois-de-menuiserie-exotique',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 6,
      nom: 'Parquet',
      descriptif: 'Massif ou contrecollé - Pose à clouer, visser ou coller',
      path_img: null,
      id_cat_parent: 0,
      slug: 'parquet',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 7,
      nom: 'Lambris',
      descriptif: 'Usage intérieur ou extérieur sous abri',
      path_img: null,
      id_cat_parent: 0,
      slug: 'lambris',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 8,
      nom: 'Bois autoclavé',
      descriptif: 'Traités par imprégnation à cœur pour usage extérieur - Garantis de 10 à 20ans',
      path_img: null,
      id_cat_parent: 0,
      slug: 'bois-autoclave',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 9,
      nom: 'Plinthe et Surplinthe',
      descriptif: 'En Pin, Sapin Nord blanc ou MDF prépeint blanc',
      path_img: null,
      id_cat_parent: 0,
      slug: 'plinthe',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 10,
      nom: 'Planches',
      descriptif: 'Coffrage, usages divers',
      path_img: null,
      id_cat_parent: 0,
      slug: 'planches',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 11,
      nom: 'Moulures - Tasseaux',
      descriptif: 'Pin sans nœuds ou chêne - Non aboutés',
      path_img: null,
      id_cat_parent: 0,
      slug: 'moulures-tasseaux',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 12,
      nom: 'Portes / blocs portes',
      descriptif: 'Portes seules et blocs-portes - Usage intérieur - Alvéolaire/Ame pleine/Coupe-feu 30min ou 60min - De nombreuses références en stock, nous consulter',
      path_img: null,
      id_cat_parent: 0,
      slug: 'portes-blocs-portes',
      is_item: 1,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 13,
      nom: 'Colles et produits de traitement',
      descriptif: 'Colle à bois - bois et matériaux / Insecticides et fongicides / Saturateur',
      path_img: null,
      id_cat_parent: 0,
      slug: 'colles-et-produits-de-traitement',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 14,
      nom: 'Quincaillerie',
      descriptif: 'Visserie Zinguée/ Inox/ Equerres/ Sabots de charpente/ Pieds de poteaux',
      path_img: null,
      id_cat_parent: 0,
      slug: 'quincaillerie',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 15,
      nom: 'Sapin du nord',
      descriptif: 'Provenance Pays du Nord de l\'Europe - Menuiserie intérieure/extérieure',
      path_img: null,
      id_cat_parent: 0,
      slug: 'sapin-du-nord',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 16,
      nom: 'Volets',
      descriptif: 'Lame à volets - Barres et écharpes - Battement \nLame à volets - Barres et écharpes - Battement',
      path_img: null,
      id_cat_parent: 0,
      slug: 'volets',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 17,
      nom: 'Panneaux',
      descriptif: '',
      path_img: null,
      id_cat_parent: 0,
      slug: 'panneaux',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 18,
      nom: 'Jalons',
      descriptif: '',
      path_img: null,
      id_cat_parent: 0,
      slug: 'jalons',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 19,
      nom: 'Fabrication sur mesure',
      descriptif: 'Plateaux de table - Bureau - Meuble Vasque - Comptoir - Petit mobilier - Projet à deviser sur place',
      path_img: null,
      id_cat_parent: 0,
      slug: 'fabrication-sur-mesure',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 20,
      nom: 'Chêne',
      descriptif: 'Chêne de Bourgogne - Plot - Séchage naturel - Epaisseurs 20-27-34-41-54mm',
      path_img: null,
      id_cat_parent: 1,
      slug: 'bois-menuiserie-chene',
      is_item: 1,
      section: null,
      longueur: null,
      essence: null,
      type: 'BME',
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 21,
      nom: 'Chataigner',
      descriptif: 'Châtaignier de Dordogne - Plots ou avivés - Séchage naturel ou séchoir - Epaisseurs 20-27-34-45-54mm',
      path_img: null,
      id_cat_parent: 1,
      slug: 'chataigner',
      is_item: 1,
      section: 'Epaisseur: 20-27-34-45-54',
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 22,
      nom: 'Pin sans nœud',
      descriptif: 'Pin trié sans nœud des Landes - Avivés - Séchage naturel - Epaisseurs 27-32-41-52mm',
      path_img: null,
      id_cat_parent: 1,
      slug: 'pin-sans-nœud',
      is_item: 1,
      section: 'Sections: \n- 27*215\n- 32 * toutes largeur\n- 41*215\n- 52*215',
      longueur: 'Longueur: 2.4m',
      essence: 'Pin',
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 23,
      nom: 'Frêne',
      descriptif: 'Frêne blanc de Bourgogne/ Franche comté - Avivés - Séchage naturel - Epaisseurs 27-41-54mm',
      path_img: null,
      id_cat_parent: 1,
      slug: 'frene',
      is_item: 1,
      section: 'Epaisseur: 27-41-54',
      longueur: null,
      essence: 'Frêne',
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 24,
      nom: 'Hêtre',
      descriptif: 'Hêtre de Bourgogne/ Franche comté - Avivés - Séchage naturel - Epaisseurs 27-41-54mm',
      path_img: null,
      id_cat_parent: 1,
      slug: 'hetre',
      is_item: 1,
      section: 'Epaisseur: 27-41-54',
      longueur: null,
      essence: 'Hêtre',
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 25,
      nom: 'Tilleul',
      descriptif: 'Tilleul de Bourgogne/ Franche comté - Plots - Séchage naturel - Epaisseurs 27-45mm',
      path_img: null,
      id_cat_parent: 1,
      slug: 'tilleul',
      is_item: 1,
      section: 'Epaisseur: 27-45',
      longueur: null,
      essence: 'Tilleul',
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 26,
      nom: 'Erable Sycomore',
      descriptif: 'Sycomore de Bourgogne/ Franche comté - Plot - Séchage naturel - Epaisseurs 27mm ou autre selon arrivage',
      path_img: null,
      id_cat_parent: 1,
      slug: 'erable-sycomore',
      is_item: 1,
      section: 'Epaisseur: 27-34',
      longueur: null,
      essence: 'Erable/Sycomore',
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 27,
      nom: 'Merisier',
      descriptif: 'Merisier de Bourgogne - Plot - Séchage naturel - Epaisseur 34mm ou autre selon arrivage',
      path_img: null,
      id_cat_parent: 1,
      slug: 'merisier',
      is_item: 1,
      section: 'Epaisseur: 27-34',
      longueur: null,
      essence: 'Merisier',
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 28,
      nom: 'Liteaux et contre-liteaux',
      descriptif: '27x40mm - Longueur 4m / 14x38mm- Longueur 3m',
      path_img: null,
      id_cat_parent: 2,
      slug: 'liteaux-contre-liteaux',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 29,
      nom: 'Chevrons',
      descriptif: 'Section:\n- 6x8cm - Longueur 3m, 3,5m, 4m et 5m / \n\nSection \n- 11x10cm - Longueur 2,5m, 3m, 3,5m \n\n- Autres longueurs sur commande',
      path_img: null,
      id_cat_parent: 2,
      slug: 'chevrons',
      is_item: 1,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 30,
      nom: 'Solivettes',
      descriptif: 'Section 15x5cm - Longueur 3m, 3,5m, 4m, 5m / Section 22x4cm - Longueur 3,5m, 4m, 5m - Autres longueurs sur commande',
      path_img: null,
      id_cat_parent: 2,
      slug: 'solivettes',
      is_item: 1,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 31,
      nom: 'Madriers',
      descriptif: 'Section 18x8cm - Longueur 3m, 3,5m, 4m, 5m / Section 22x8cm - Longueur 4m, 5m, 6m / Section 22x10cm - Longueur 4m, 5m, 6m / Section 25x10cm - Longueur 7m - Autres longueurs sur commande',
      path_img: null,
      id_cat_parent: 2,
      slug: 'madriers',
      is_item: 1,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 32,
      nom: 'Planches d\'échafaudage',
      descriptif: 'Section 25x5cm - Longueur 4m (1er choix)',
      path_img: null,
      id_cat_parent: 2,
      slug: 'planches-echafaudage',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 33,
      nom: 'Voliges',
      descriptif: 'Section 15x200mm - Longueur 3m - Autres longueurs sur commande',
      path_img: null,
      id_cat_parent: 2,
      slug: 'voliges',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 34,
      nom: 'Poteaux',
      descriptif: 'Section 20x20cm - Longueur 2,5m, 3,5m, 5m, 6,5m - Autres longueurs sur commande',
      path_img: null,
      id_cat_parent: 2,
      slug: 'poteaux',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 35,
      nom: 'Débit sur liste',
      descriptif: 'Toutes sections sur mesure sur commande (Epicéa / Douglas / Chêne)',
      path_img: null,
      id_cat_parent: 2,
      slug: 'debit-sur-liste',
      is_item: 1,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('2024-01-17T11:39:35'),
      updatedAt: new Date('2024-01-17T11:39:35'),
    },
    {
      id: 36,
      nom: 'Pin sylvestre',
      descriptif: 'Traitées CL4 - Lisses ou rainurées - Choix sans nœud / petits noeuds - Section 145x22mm - Longueur 3m, 4m',
      path_img: null,
      id_cat_parent: 3,
      slug: 'pin-sylvestre',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 37,
      nom: 'Macaranduba',
      descriptif: 'Rouge foncé - Origine Amérique du Sud - Naturellement CL5 - Section 145x22mm - Longueurs en fonction des arrivages',
      path_img: null,
      id_cat_parent: 3,
      slug: 'mame-terrasse-macaranduba',
      is_item: 1,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 38,
      nom: 'Gamme Vivre en bois',
      descriptif: 'Gamme disponible sur commande - Catalogue sur place ou à consulter sur Internet.',
      path_img: null,
      id_cat_parent: 3,
      slug: 'gamme-vivre-en-bois',
      is_item: 1,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 39,
      nom: 'Epicéa',
      descriptif: 'Volige section 15x200mm - Longueur 3m - Traité CL2 / Volige section 18x150mm - Longueur 3m - Traité CL3 Marron',
      path_img: null,
      id_cat_parent: 4,
      slug: 'epicea',
      is_item: 0,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 40,
      nom: 'Pin Sylvestre',
      descriptif: 'Clin Section 135x22mm - Traité CL4 - Profil élégie - Lames bouvetées, rabotées, longueurs selon arrivage.',
      path_img: null,
      id_cat_parent: 4,
      slug: 'bardage-pin-sylvestre',
      is_item: 1,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },
    {
      id: 41,
      nom: 'Pin',
      descriptif: 'Planches brutes en Pin des Landes sans traitement - Toutes largeurs - Longueur 2m',
      path_img: null,
      id_cat_parent: 4,
      slug: 'pin',
      is_item: 1,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      createdAt: new Date('1899-12-31T00:00:00'),
      updatedAt: new Date('1899-12-31T00:00:00'),
    },    
    // Ajoutez les autres catégories ici si nécessaire.
    // Ajoutez ici la suite des catégories nécessaires.
    // Continuez ainsi pour les autres catégories...
  ];

  try {
    await Category.bulkCreate(categories, { updateOnDuplicate: ['nom'] });
    console.log("All categories initialized successfully.");
  } catch (error) {
    console.error("Error initializing categories:", error);
  }
};