/*
 * Script d'initialisation des items
 */
const { Item } = require('../../api/item/item.model');

module.exports = async function initItems() {
  const items = [
    {
      id: 18,
      nom: 'Pin 15m',
      path_img: 'img/images/bois.jpg',
      section: 'Toutes largeurs',
      longueur: 'Longueur: 2m/2.4m',
      essence: 'Pin',
      type: null,
      norme: null,
      descriptif: null,
      id_category: 33,
      slug: 'volige-pin',
      createdAt: new Date('2023-07-04T19:26:34'),
      updatedAt: null
    },
    {
      id: 19,
      nom: 'Epicéa CL2',
      path_img: 'img/images/bois.jpg',
      section: 'Section: 15*200',
      longueur: 'Longueur: 3m',
      essence: 'Epicéa',
      type: null,
      norme: null,
      descriptif: null,
      id_category: 33,
      slug: 'volige-epicea-cl2',
      createdAt: new Date('2023-07-04T19:26:40'),
      updatedAt: null
    },
    {
      id: 20,
      nom: 'Epicéa CL3',
      path_img: 'img/images/bois.jpg',
      section: 'Section: 18*150',
      longueur: 'Longueur: 3m/4m',
      essence: null,
      type: null,
      norme: null,
      descriptif: null,
      id_category: 33,
      slug: 'volige-epicea-cl3',
      createdAt: new Date('2023-07-04T19:26:44'),
      updatedAt: null
    },
    {
      id: 21,
      nom: '1/2 Liteaux',
      path_img: 'img/images/bois.jpg',
      section: 'Section: 14*38',
      longueur: 'Longueur: 3m',
      essence: null,
      type: null,
      norme: null,
      descriptif: null,
      id_category: 28,
      slug: 'demi-liteaux',
      createdAt: new Date('2023-07-04T19:26:47'),
      updatedAt: null
    },
    {
      id: 22,
      nom: 'Liteaux',
      path_img: 'img/images/bois.jpg',
      section: 'Section: \n- 27x40mm - Longueur 4m \n- 14x38mm- Longueur 3m ',
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      descriptif: 'Section: \n- 27x40mm - Longueur 4m \n- 14x38mm- Longueur 3m ',
      id_category: 28,
      slug: 'liteaux',
      createdAt: new Date('2023-07-04T19:26:48'),
      updatedAt: null
    },
    {
      id: 24,
      nom: 'Poteaux',
      path_img: 'img/images/bois.jpg',
      section: 'Section: 200*200',
      longueur: 'Longueur: 2.5m/3.5m/5m/6.5m',
      essence: null,
      type: null,
      norme: null,
      descriptif: null,
      id_category: 34,
      slug: 'poteaux',
      createdAt: new Date('2023-07-04T19:26:49'),
      updatedAt: null
    },
    {
      id: 25,
      nom: 'Poteaux Chêne',
      path_img: 'img/images/bois.jpg',
      section: 'Section: 180*180',
      longueur: 'Lonueur: 3m',
      essence: 'Chêne',
      type: null,
      norme: null,
      descriptif: null,
      id_category: 34,
      slug: 'poteaux-chene',
      createdAt: new Date('2023-07-04T19:26:49'),
      updatedAt: null
    },
    {
      id: 26,
      nom: 'Poteaux Iroko',
      path_img: 'img/images/bois.jpg',
      section: 'Section: 200*200',
      longueur: 'Lonueur: 2.8m',
      essence: 'Iroko',
      type: null,
      norme: null,
      descriptif: null,
      id_category: 34,
      slug: 'poteaux-iroko',
      createdAt: new Date('2023-07-04T19:26:50'),
      updatedAt: null
    },
    {
      id: 27,
      nom: 'Planche Echaffaudage',
      path_img: 'img/images/bois.jpg',
      section: 'Section: 250*50',
      longueur: 'Longueur: 4m',
      essence: null,
      type: null,
      norme: null,
      descriptif: null,
      id_category: 32,
      slug: 'planche-echaffaudage',
      createdAt: new Date('2023-07-04T19:26:51'),
      updatedAt: null
    },
    {
      id: 28,
      nom: 'Planche Coffrage',
      path_img: 'img/images/bois.jpg',
      section: 'Section: 27*120 - 27*250',
      longueur: 'Longueur: 4m',
      essence: null,
      type: null,
      norme: null,
      descriptif: null,
      id_category: 32,
      slug: 'planche-coffrage',
      createdAt: new Date('2023-07-04T19:26:51'),
      updatedAt: null
    },
    {
      id: 33,
      nom: 'Pin Sylvestre traité CL4, Rustique',
      path_img: 'img/images/bois.jpg',
      section: 'Section: 145*22',
      longueur: 'Longueur: 3m/4M',
      essence: 'Pin',
      type: 'Rustique',
      norme: null,
      descriptif: '',
      id_category: 36,
      slug: 'pin-rustique',
      createdAt: new Date('2023-07-04T19:26:54'),
      updatedAt: null
    },
    {
      id: 34,
      nom: 'Pin Sylvestre traité CL4, petit Nœud',
      path_img: 'img/images/bois.jpg',
      section: 'Section: 145*22',
      longueur: 'Longueur: 2.9m/3.9m',
      essence: null,
      type: 'Petit Noeud',
      norme: null,
      descriptif: null,
      id_category: 36,
      slug: 'pin-petit-noeud',
      createdAt: new Date('2023-07-04T19:26:55'),
      updatedAt: null
    },
    {
      id: 35,
      nom: 'Pin Sylvestre traité CL4, Sans nœud',
      path_img: 'img/images/bois.jpg',
      section: 'Section: 145*22',
      longueur: 'Longueur: 2.9m/3.9m',
      essence: null,
      type: 'Sans noeud',
      norme: null,
      descriptif: null,
      id_category: 36,
      slug: 'pin-sans-noeud',
      createdAt: new Date('2023-07-04T19:26:56'),
      updatedAt: null
    },
    {
      id: 38,
      nom: 'Epicéa CL3',
      path_img: 'img/images/bois.jpg',
      section: 'Section: 18*150',
      longueur: 'Longueur: 3m/4m',
      essence: 'Epicéa',
      type: null,
      norme: null,
      descriptif: 'Brut traité CL3',
      id_category: 39,
      slug: 'bardage-epicea-cl3',
      createdAt: new Date('2023-07-04T19:26:57'),
      updatedAt: null
    },
    {
      id: 39,
      nom: 'Epicé CL2',
      path_img: 'img/images/bois.jpg',
      section: 'Section: 15*200',
      longueur: 'Longueur: 3m',
      essence: 'Epicéa',
      type: null,
      norme: null,
      descriptif: 'Brut traité CL2',
      id_category: 39,
      slug: 'bardage-epicea-cl2',
      createdAt: new Date('2023-07-04T19:27:00'),
      updatedAt: null
    },
    {
      id: 40,
      nom: 'Lames à volets',
      path_img: null,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      descriptif: 'Essence : Sapin nord blanc, sans chanfreins - section 28x105mm - Longueurs disponibles 1800, 2100, 2400, 2700mm\n',
      id_category: 90,
      slug: 'lames-volet-sapin',
      createdAt: new Date('2023-07-04T19:27:04'),
      updatedAt: null
    },
    {
      id: 41,
      nom: 'Echarpes à volets',
      path_img: null,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      descriptif: 'Echarpes et barres - Sapin nord blanc, section 28x95mm - Longueur 2400mm\n',
      id_category: 90,
      slug: 'echarpes',
      createdAt: new Date('2023-07-04T19:27:05'),
      updatedAt: null
    },
    {
      id: 42,
      nom: 'Battements à volets',
      path_img: null,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      descriptif: 'Battement ou couvre-joint - Sapin nord blanc, section 70x22mm - Longueur 2700mm\n',
      id_category: 90,
      slug: 'battements',
      createdAt: new Date('2023-07-04T19:27:06'),
      updatedAt: null
    },
    {
      id: 43,
      nom: 'Lames à volets Palapi',
      path_img: null,
      section: null,
      longueur: null,
      essence: null,
      type: null,
      norme: null,
      descriptif: 'Essence Palapi - origine Asie - Section 95x28mm - Longueur 2,70m \n',
      id_category: 93,
      slug: 'palapi',
      createdAt: new Date('2023-07-04T19:27:06'),
      updatedAt: null
    }
  ];

  try {
    await Item.bulkCreate(items, { updateOnDuplicate: ['nom'] });
    console.log("Items initialized successfully.");
  } catch (error) {
    console.error("Error initializing items:", error);
  }
};
